version: '3.8'

services:
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: ai_etl_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01_init_db.sql:ro
    networks:
      - ai_etl_network
    env_file:
      - ./.env

  redis:
    image: redis:7.2-alpine
    container_name: ai_etl_redis
    ports:
      - "6379:6379"
    networks:
      - ai_etl_network

  backend:
    build: ./backend             
    container_name: ai_etl_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app           
    environment:
      - DB_HOST=postgres          
      - DB_PORT=5432
    depends_on:
      - postgres                
    networks:
      - ai_etl_network
    env_file:
      - ./.env

  data-pipeline:
    build: ./data-pipeline
    container_name: ai_etl_pipeline
    volumes:
      - ./data-pipeline:/app
      - spark_events:/tmp/spark-events
    environment:
      - DB_HOST=postgres 
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - ai_etl_network
    env_file:
      - ./.env

  spark-history-server:
    image: apache/spark:3.5.0
    user: "0:0"
    environment:
      SPARK_HISTORY_OPTS: "-Dspark.history.fs.logDirectory=file:///tmp/spark-events"
    command: >
      bash -c
      "/opt/spark/sbin/start-history-server.sh &&
      tail -f /dev/null"
    ports:
      - "18080:18080"
    volumes:
      - spark_events:/tmp/spark-events

volumes:
  postgres_data:
  spark_events:

networks:
  ai_etl_network:
    driver: bridge
