import json
import os
import sys
from xml.parsers.expat import model
import psycopg2
from psycopg2 import sql
import pandas as pd
from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from pyspark.sql.types import ArrayType, FloatType, StringType
from pyspark.sql.functions import pandas_udf
import torch
from config import settings

os.environ["OMP_NUM_THREADS"] = "2"
os.environ["MKL_NUM_THREADS"] = "2"
torch.set_num_threads(2)

_EMBEDDING_MODEL_CACHE = None

def get_embedding_model():
    global _EMBEDDING_MODEL_CACHE
    if _EMBEDDING_MODEL_CACHE is None:
        from sentence_transformers import SentenceTransformer
   
        _EMBEDDING_MODEL_CACHE = SentenceTransformer('BAAI/bge-small-en-v1.5', device="cpu")
    return _EMBEDDING_MODEL_CACHE

@pandas_udf(returnType=ArrayType(FloatType())) # type: ignore
def generate_embeddings_udf(text_series: pd.Series) -> pd.Series:
    """
    Generates embeddings for a series of text.
    Executes batched text vectorization across PySpark Worker nodes using HuggingFace models.
    Leverages Arrow zero-copy memory transfers and batch Matrix operations.
    """  
    model = get_embedding_model()
    
    text_list = text_series.fillna("").tolist()
  
    embeddings = model.encode(
        text_list, 
        batch_size=32, 
        show_progress_bar=False, 
        normalize_embeddings=True
    )
    
    return pd.Series(embeddings.tolist())

_LLM_PIPELINE_CACHE = None

def get_llm_pipeline():
    """
    Lazily loads a local instruction-tuned LLM in each Spark Worker process.
    """
    global _LLM_PIPELINE_CACHE, _LLM_MODEL_CACHE, _LLM_TOKENIZER_CACHE
    if _LLM_PIPELINE_CACHE is None:
        from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
        
        model_id = "Qwen/Qwen2.5-1.5B-Instruct" 
        print(f"Loading local extraction model [{model_id}] on Worker...")
        
        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=torch.float32, 
            device_map="cpu"
        )
        
        _LLM_PIPELINE_CACHE = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            max_new_tokens=256,
            temperature=0.1,
            do_sample=False
        )
    return _LLM_PIPELINE_CACHE

@pandas_udf(returnType=StringType()) # type: ignore
def extract_structured_metadata_udf(abstract_series: pd.Series) -> pd.Series:
    """
    Performs open-ended structured extraction on paper abstracts using a local Hugging Face Pipeline.
    """
    generator = get_llm_pipeline()
    results = []
    
    # Convert Pandas Series to a list for efficient processing
    texts = abstract_series.fillna("").tolist()
    
    # Construct prompt lists for batch inputs
    prompts = []
    valid_indices = []

    if generator.tokenizer is None:
        raise RuntimeError("Tokenizer failed to initialize.")
    
    for idx, text in enumerate(texts):
        if not text.strip():
            results.append((idx, json.dumps({
                "core_method": "Not specified",
                "dataset_used": "Not specified",
                "key_findings": "Not specified"
            })))
            continue
            
        system_prompt = (
            "You are an expert AI research assistant. Extract 3 fields from the abstract: "
            "1. core_method (proposed algorithm/model), "
            "2. dataset_used (datasets/benchmarks used, or 'Not specified'), "
            "3. key_findings (one-sentence main conclusion). "
            "Output STRICT JSON format only with keys: core_method, dataset_used, key_findings. No markdown."
        )
        
        # Format messages matching Qwen / Llama Chat Template standard
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Abstract: {text}"}
        ]

        
        formatted_prompt = generator.tokenizer.apply_chat_template(
            messages, 
            tokenize=False, 
            add_generation_prompt=True
        )
        prompts.append((idx, formatted_prompt))

    if prompts:
        indices, batch_prompts = zip(*prompts)
        
        try:
            # Batch call local model generation (pipeline supports passing a list for batch inference)
            outputs = generator(
                list(batch_prompts), 
                batch_size=16,          # Internal batch size to prevent out-of-memory errors
                pad_token_id=generator.tokenizer.eos_token_id
            )
            
            for idx, output in zip(indices, outputs):
                # Extract text generated by the model
                generated_text = output[0]["generated_text"]
                # Slice out the model response portion by removing the prompt prefix
                response_content = generated_text[len(batch_prompts[indices.index(idx)]):].strip()
                
                # Clean up any potential markdown code blocks (e.g., ```json ... ```)
                clean_json_str = response_content.replace("```json", "").replace("```", "").strip()
                
                # Try parsing JSON to ensure valid syntax
                parsed = json.loads(clean_json_str)
                results.append((idx, json.dumps({
                    "core_method": parsed.get("core_method", "Not specified"),
                    "dataset_used": parsed.get("dataset_used", "Not specified"),
                    "key_findings": parsed.get("key_findings", "Not specified")
                })))
                
        except Exception as e:
            # Fault tolerance fallback: Assign default structure if parsing fails for a batch to prevent task failure
            print(f"⚠️ LLM Extraction parsing warning: {str(e)}")
            for idx, _ in prompts:
                results.append((idx, json.dumps({
                    "core_method": "Extraction Error",
                    "dataset_used": "Extraction Error",
                    "key_findings": "Extraction Error"
                })))

    # Reorder results back to match the original Pandas Series index sequence
    results.sort(key=lambda x: x[0])
    final_json_series = pd.Series([res[1] for res in results])
    
    return final_json_series

def load_to_postgres_with_vectors(
    df: DataFrame, 
    pg_url: str, 
    pg_table: str, 
    pg_properties: dict,
    num_partitions: int = 8
):
    """
    Bulk loads DataFrame into PostgreSQL using Spark JDBC with a Staging Table pattern,
    followed by an atomic UPSERT operation casting string representations to pgvector type.
    """
    if df.isEmpty():
        print("[Load] No valid records to write to PostgreSQL.")
        return

    stage_table = f"{pg_table}_vector_stage"
    
    print(f"[Load] Preparing records for staging table '{stage_table}'...")

    # Format vector array into pgvector compatible string format: '[0.1, 0.2, ...]'
    formatted_df = df.withColumn(
        "embedding_str", 
        F.concat(F.lit("["), F.array_join(F.col("embedding"), ","), F.lit("]"))
    )

    staged_df = (
        formatted_df.select(
            "paper_id",
            "title",
            "abstract",
            "authors",
            "categories",
            "url",
            "published_date",
            "published_year",
            "ingested_at",
            "embedding_str",
            "metadata_json"
        )
        .dropDuplicates(["paper_id"])
        .repartition(num_partitions)
    )

    print(f"[Load] JDBC bulk writing to staging table '{stage_table}'...")

    try:
        print("=== Spark Physical Execution Plan ===")
        staged_df.explain(True)
        print("=====================================")

        (
            staged_df.write
            .format("jdbc")
            .option("url", pg_url)
            .option("dbtable", stage_table)
            .option("user", pg_properties["user"])
            .option("password", pg_properties["password"])
            .option("driver", "org.postgresql.Driver")
            .option("reWriteBatchedInserts", "true")
            .option("batchsize", "200")
            .option("stringtype", "unspecified")  
            .option("isolationLevel", "READ_COMMITTED")
            .mode("append")
            .save()
        ) 
        print(f"✅ [Load] Staging table '{stage_table}' created & populated successfully!")

    except Exception as e:
        print(f"❌ [Load] JDBC Ingestion failed: {str(e)}")
        raise e

    # Merge Staging data into Target Table with explicit Vector Type Cast
    print(f"[Load] Merging & Upserting to final table '{pg_table}' with vector cast...")

    conn = None
    cursor = None

    try:
        conn = psycopg2.connect(
            host=settings.db_host,
            port=settings.db_port,
            database=settings.db_name,
            user=pg_properties["user"],
            password=pg_properties["password"],
        )
        cursor = conn.cursor()

        # SQL Upsert query: Casts embedding_str to ::vector type on insertion
        merge_query = sql.SQL(
            """
            INSERT INTO {target} (
                paper_id,
                title,
                abstract,
                authors,
                categories,
                url,
                published_date,
                published_year,
                ingested_at,
                embedding,
                metadata
            )
            SELECT
                paper_id,
                title,
                abstract,
                authors,
                categories,
                url,
                published_date,
                published_year,
                ingested_at,
                embedding_str::vector AS embedding,
                metadata_json::jsonb AS metadata
            FROM {stage}
            ON CONFLICT (paper_id) DO UPDATE SET
                title = EXCLUDED.title,
                abstract = EXCLUDED.abstract,
                authors = EXCLUDED.authors,
                categories = EXCLUDED.categories,
                url = EXCLUDED.url,
                published_date = EXCLUDED.published_date,
                published_year = EXCLUDED.published_year,
                ingested_at = EXCLUDED.ingested_at,
                embedding = EXCLUDED.embedding,
                metadata = EXCLUDED.metadata;
            """
        ).format(
            target=sql.Identifier(pg_table),
            stage=sql.Identifier(stage_table),
        )

        cursor.execute(merge_query)
        conn.commit()

        print(f"✅ [Load] Successfully upserted records with vectors into '{pg_table}'!")
        
        print("[Load] Creating indexes on target table after bulk load...")
        
        index_queries = [
            "CREATE INDEX IF NOT EXISTS idx_published_year ON arxiv_documents(published_year);",
            "CREATE INDEX IF NOT EXISTS idx_categories ON arxiv_documents(categories);",
            
            """
            CREATE INDEX IF NOT EXISTS idx_arxiv_fts ON arxiv_documents 
            USING gin (
                (setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                 setweight(to_tsvector('english', coalesce(abstract, '')), 'B'))
            );
            """,
            
            """
            CREATE INDEX IF NOT EXISTS idx_arxiv_embedding_hnsw ON arxiv_documents 
            USING hnsw (embedding vector_cosine_ops) 
            WITH (m = 16, ef_construction = 64);
            """
        ]

        for idx_sql in index_queries:
            cursor.execute(idx_sql)
        
        conn.commit()
        print("✅ [Load] All indexes (including GIN and HNSW) created successfully!")

        # Drop temporary staging table after successful transaction
        cursor.execute(
            sql.SQL("DROP TABLE IF EXISTS {stage};").format(
                stage=sql.Identifier(stage_table),
            )
        )
        conn.commit()

    except Exception as error:
        if conn is not None:
            conn.rollback()
        print(f"❌ [Load] PostgreSQL vector upsert failed: {error}")
        raise

    finally:
        if cursor is not None:
            cursor.close()
        if conn is not None:
            conn.close()
            print("PostgreSQL Connection Closed.")

def run_embeddings_pipeline():
    """
    Executes The Vector Embedding Pipeline: Reads Silver Parquet Lake, executes Pandas UDF vectorization,
    and bulk writes to PostgreSQL pgvector.
    """
    spark = (
        SparkSession.builder
        .appName("ArXiv_Vector_Embedding_Pipeline")
        .config("spark.jars.packages", settings.postgres_jar_maven)
        .config("spark.driver.memory", settings.spark_driver_memory)
        .config("spark.executor.memory", settings.spark_executor_memory)
        .config("spark.sql.execution.arrow.pyspark.enabled", "true")
        .config("spark.eventLog.enabled", "true")
        .config("spark.eventLog.dir", "file:///tmp/spark-events")
        .master("local[6]")
        .getOrCreate()
    )
    spark.conf.set("spark.sql.execution.arrow.maxRecordsPerBatch", "1000") 
    #spark.conf.set("spark.sql.adaptive.enabled", "true")
    #spark.conf.set("spark.sql.adaptive.coalescePartitions.enabled", "true")

    try:
        # Load cleaned data from Silver Parquet Data Lake
        print(f"Reading cleaned parquet from: {settings.datalake_path}")
        df = spark.read.parquet(settings.datalake_path)

        # Construct input string for embeddings by combining Title and Abstract
        df_text = df.withColumn(
            "embedding_text", 
            F.concat_ws(". ", F.col("title"), F.col("abstract"))
        )

        df_text = df_text.repartition(100)
        spark.conf.set("spark.sql.execution.arrow.maxRecordsPerBatch", "100")

        print("Extracting structured metadata via LLM UDF...")
        df_structured = df_text.withColumn(
            "metadata_json", 
            extract_structured_metadata_udf(F.col("abstract"))# type: ignore
        )

        print("Computing Vector Embeddings via PySpark Pandas UDF...")
        df_embedded = df_structured.withColumn(
            "embedding", 
            generate_embeddings_udf(F.col("embedding_text")) # type: ignore
        ).drop("embedding_text")

        # Bulk ingest into PostgreSQL with pgvector schema support
        pg_config = {
            "url": settings.jdbc_url,
            "table": settings.target_table,
            "properties": {
                "user": settings.db_user,
                "password": settings.db_password,
            },
        }

        load_to_postgres_with_vectors(
            df=df_embedded,
            pg_url=pg_config["url"],
            pg_table=pg_config["table"],
            pg_properties=pg_config["properties"],
            num_partitions=settings.spark_partitions
        )

    except Exception as e:
        print(f"❌ Vector Embedding Pipeline Failed: {str(e)}")
        sys.exit(1)
    finally:
        spark.stop()
        print("Spark Session Terminated.")

if __name__ == "__main__":
    run_embeddings_pipeline()